### ISSUE TITLE
el-tree拓展

### ISSUE THREAD

**Issue by default-github** [Plutossy/tree-transfer-vue3#2]
请问插件里面的树组件有原el-tree的属性和方法及插槽内容吗，比如节点的点击事件等等，就是说element-plus官网的el-tree组件的内容，在这个插件里也可以使用吗，我看到插件里文档内容好像没有那么多

**Comment by Plutossy** [comment]
还没有添加，这里只添加了拖拽相关的事件。后续会考虑加上
