### ISSUE TITLE
穿梭框高度

### ISSUE THREAD

**Issue by default-github** [Plutossy/tree-transfer-vue3#3]
穿梭框里面数据好像没有滚动条，el-transfer里面数据内容是有滚动条的，另外想请问作者组件tree-transfer-vue3的源码可以分享吗，放自己项目里比较方便修改内部的内容

**Comment by Plutossy** [comment]
package里面的就是源代码

**Comment by Plutossy** [comment]
其实，可以改改高度，设置一下滚动应该就可以

**Comment by default-github** [comment]
> 其实，可以改改高度，设置一下滚动应该就可以

用:deep()改了组件的高度，还需要再改el-tree的高度，可以了，靴靴泥
